#app
server:
    port: 8091
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

#spring
spring:
  application:
    name: reward-api
  devtools:
    restart:
      enabled: false

  # H2 DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #schema: classpath:/db/schema-h2.sql
    #data: classpath:/db/data-h2.sql
    url: jdbc:mysql://127.0.0.1:3306/pos_reward?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yangdi
    platform: mysql
    initialize: true
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /console

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.linrry.auth.zuul.reward.api.entity
  #typeEnumsPackage: com.linrry.auth.zuul.sys.api.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  level: error
